### PR TITLE
First release of this plugin

### PR DESCRIPTION
**Pull request by artalat**

### CODE REVIEW

**Comment by artalat** [comment]
@ammarkhan967 lets first do an analysis of how many tests are written, and where we stand right now with @asadmogul's working merging here. Then break add new tests to sub-PRs, and estimate testing individual components, APIs one at a time rather than estimating and tracking this big PR?

cc: @hassans-be

**Comment by ammarkhan967** [comment]
> @ammarkhan967 lets first do an analysis of how many tests are written, and where we stand right now with @asadmogul's working merging here. Then break add new tests to sub-PRs, and estimate testing individual components, APIs one at a time rather than estimating and tracking this big PR?
> 
> cc: @hassans-be

okay sir

**Comment by hassans-be** [comment]
@danial24 when can we complete this pull request?

**Pull request merged**
